-- MySQL Script generated by MySQL Workbench
-- Thursday 21 September 2017 04:42:27 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Primary Keys, Strong and Weak Entities mentioned in COMMENT after CREATE TABLES. 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `Actor_ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Actor_ID`))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Actor_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `Movie_ID` INT NOT NULL AUTO_INCREMENT,
  `Movie_name` VARCHAR(45) NOT NULL,
  `Actor_ID` INT NOT NULL,
  PRIMARY KEY (`Movie_ID`),
  INDEX `fk_Movie_1_idx` (`Actor_ID` ASC),
  CONSTRAINT `fk_Movie_1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`Actor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Movie_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`TVseries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TVseries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TVseries` (
  `TVseries_ID` INT NOT NULL AUTO_INCREMENT,
  `TVseries_name` VARCHAR(45) NOT NULL,
  `Actor_ID` INT NOT NULL,
  PRIMARY KEY (`TVseries_ID`),
  INDEX `fk_TVseries_1_idx` (`Actor_ID` ASC),
  CONSTRAINT `fk_TVseries_1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`Actor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - TVSeries_ID ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
