-- MySQL Script generated by MySQL Workbench
-- Thursday 21 September 2017 04:38:20 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Primary Keys, Strong and Weak Entities mentioned in COMMENT after CREATE TABLES. 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Employee_id` INT(3) NOT NULL AUTO_INCREMENT,
  `assigned_project_id` INT(2) NOT NULL,
  `reports_to_EID` INT(3) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NULL,
  `Employee_contact` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Employee_id`),
  INDEX `fk_employee_1_idx` (`reports_to_EID` ASC),
  UNIQUE INDEX `Employee_contact_UNIQUE` (`Employee_contact` ASC),
  CONSTRAINT `fk_employee_1`
    FOREIGN KEY (`reports_to_EID`)
    REFERENCES `mydb`.`Employee` (`Employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'Strong Entity.\nPrimary Key - Employee_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `Project_id` INT(2) NOT NULL AUTO_INCREMENT,
  `Project_name` VARCHAR(50) NOT NULL,
  `project_manager_EID` INT(3) NOT NULL,
  PRIMARY KEY (`Project_id`),
  INDEX `fk_project_1_idx` (`project_manager_EID` ASC),
  CONSTRAINT `fk_project_1`
    FOREIGN KEY (`project_manager_EID`)
    REFERENCES `mydb`.`Employee` (`Employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'Strong Entity.\nPrimary Key - Project_ID ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
