-- MySQL Script generated by MySQL Workbench
-- Thursday 21 September 2017 04:45:49 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Primary Keys, Strong and Weak Entities mentioned in COMMENT after CREATE TABLES. 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Branches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Branches` (
  `Branch_ID` INT NOT NULL,
  `Branch_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Branch_ID`))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Branch_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Accounts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `Account_ID` INT NOT NULL AUTO_INCREMENT,
  `Account_num` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Branch_ID` INT NOT NULL,
  PRIMARY KEY (`Account_ID`),
  UNIQUE INDEX `index2` (`Customer_ID` ASC, `Branch_ID` ASC),
  INDEX `fk_Accounts_1_idx` (`Branch_ID` ASC),
  CONSTRAINT `fk_Accounts_1`
    FOREIGN KEY (`Branch_ID`)
    REFERENCES `mydb`.`Branches` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Account_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_name` VARCHAR(45) NOT NULL,
  `Account_ID` INT NULL,
  PRIMARY KEY (`Customer_ID`),
  INDEX `fk_Customer_1_idx` (`Account_ID` ASC),
  CONSTRAINT `fk_Customer_1`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `mydb`.`Accounts` (`Account_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Customer_ID ';

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Accounts_BEFORE_INSERT` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Accounts_BEFORE_INSERT` BEFORE INSERT ON `Accounts` FOR EACH ROW
BEGIN
	IF ((SELECT(COUNT(*)) FROM Accounts a 
		WHERE NEW.Customer_ID = a.Customer_ID 
		AND NEW.Branch_ID = a.Branch_ID) > 0)
    THEN SIGNAL SQLSTATE '45000';
		 SET MESSAGE_TEXT = 'A customer cannot have multiple accounts in the same branch.';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
