-- MySQL Script generated by MySQL Workbench
-- Thursday 21 September 2017 04:39:35 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Primary Keys, Strong and Weak Entities mentioned in COMMENT after CREATE TABLES. 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `Restaurant_ID` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_name` VARCHAR(45) NOT NULL,
  `Restaurant_location` VARCHAR(45) NOT NULL,
  `Restaurant_contact` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Restaurant_ID`),
  UNIQUE INDEX `Restaurant_contact_UNIQUE` (`Restaurant_contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Restaurant_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Delivery_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Delivery_person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Delivery_person` (
  `Delivery_person_ID` INT NOT NULL AUTO_INCREMENT,
  `Delivery_person_firstname` VARCHAR(45) NOT NULL,
  `Delivery_person_lastname` VARCHAR(45) NULL,
  `Delivery_person_contact` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Delivery_person_ID`),
  UNIQUE INDEX `Delivery_person_contact_UNIQUE` (`Delivery_person_contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Delivery_person_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_firstname` VARCHAR(45) NOT NULL,
  `Customer_lastname` VARCHAR(45) NULL,
  `Customer_address` VARCHAR(100) NOT NULL,
  `Customer_contact` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Customer_ID`),
  UNIQUE INDEX `Customer_contact_UNIQUE` (`Customer_contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Customer_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `Order_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `Delivery_person_ID` INT NOT NULL,
  `Order_date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Delivery_date_time` DATETIME NOT NULL DEFAULT 9999-12-31 23:59:59,
  PRIMARY KEY (`Order_ID`),
  INDEX `fk_Order_1_idx` (`Customer_ID` ASC),
  INDEX `fk_Order_2_idx` (`Restaurant_ID` ASC),
  INDEX `fk_Order_3_idx` (`Delivery_person_ID` ASC),
  CONSTRAINT `fk_Order_1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `mydb`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_2`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `mydb`.`Restaurant` (`Restaurant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_3`
    FOREIGN KEY (`Delivery_person_ID`)
    REFERENCES `mydb`.`Delivery_person` (`Delivery_person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Weak Entity. \nPrimary Key - {Customer_ID, Resturant_ID, Delivery_person_ID}\nPartial Key - Order_ID (Used for Indexing purposes as Primary Key)';

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Order_BEFORE_INSERT` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Order_BEFORE_INSERT` BEFORE INSERT ON `Order` FOR EACH ROW
BEGIN
	IF (NEW.Order_date_time < (SELECT Delivery_date_time 
		FROM Orders o
		WHERE o.Customer_ID = NEW.Customer_ID))
	THEN
		SIGNAL SQLSTATE '45000';
        SET MESSAGE_TEXT = 'Customer can book from only only restaurant at a time.';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
