-- MySQL Script generated by MySQL Workbench
-- Thursday 21 September 2017 04:41:05 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Primary Keys, Strong and Weak Entities mentioned in COMMENT after CREATE TABLES. 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `Hotel_ID` INT NOT NULL AUTO_INCREMENT,
  `Hotel_name` VARCHAR(45) NOT NULL,
  `Hotel_location` VARCHAR(100) NOT NULL,
  `Hotel_contact` MEDIUMTEXT NOT NULL,
  `Stars` INT(1) NULL,
  PRIMARY KEY (`Hotel_ID`),
  UNIQUE INDEX `Hotel_contact_UNIQUE` (`Hotel_contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Hotel_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_firstname` VARCHAR(45) NOT NULL,
  `Customer_lastname` VARCHAR(45) NULL,
  `Customer_contact` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Customer_ID`),
  UNIQUE INDEX `Customer_contact_UNIQUE` (`Customer_contact` ASC))
ENGINE = InnoDB
COMMENT = 'Strong Entity.\nPrimary Key - Customer_ID ';


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Booking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `Booking_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Hotel_ID` INT NOT NULL,
  `Check_in_date` DATE NOT NULL,
  `Check_out_date` DATE NULL DEFAULT '9999-12-31',
  `Loyal` BIT NOT NULL DEFAULT false,
  PRIMARY KEY (`Booking_ID`),
  INDEX `fk_Booking_1_idx` (`Customer_ID` ASC),
  INDEX `fk_Booking_2_idx` (`Hotel_ID` ASC),
  CONSTRAINT `fk_Booking_1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `mydb`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_2`
    FOREIGN KEY (`Hotel_ID`)
    REFERENCES `mydb`.`Hotel` (`Hotel_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Weak Entity. \nPrimary Key - {Customer_ID, Hotel_ID}\nPartial Key - Booking_ID (Used for Indexing purposes as Primary Key)';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
